#!/bin/sh
INPUT=$1 # DON'T CHANGE THIS
set -e

################################################################################

SITE_NAME="Tukain"
SITE_AUTHOR="tukain"
SITE_FEED="false"
SITE_GENERATE_HTML="true"
SITE_BANNER=$(cat << EOF
⠀⠀⠀⢠⢡⢯⣟⢮⢿⢾⣯⣻⣟⣾⣵⣿⢾⡟⠕⣁⢪⣮⣳⢯⣳⢕⢧⡳⡘⣌⢳⡐⢀⠂⠐⢂⠀⡀
⠀⠀⠀⢰⢍⡾⣳⡫⣟⣫⣷⢯⣿⡱⣿⢞⣿⡝⣜⢮⣟⣷⡻⣗⡽⣪⢳⡸⣊⢆⢎⠔⡁⠐⡀⠁⡂⠀
⠀⠀⢀⠣⣸⢋⢮⠸⡕⣽⣏⣿⢊⡾⣝⡿⣺⠔⣽⣻⣯⢿⣝⢷⡝⣮⢣⢎⢖⠅⡧⢊⠔⠁⢄⠀⠌⠠
⠀⠀⡀⠢⡣⡱⡑⢕⡺⣹⢖⡯⢸⡣⣻⣝⢽⢸⡿⣯⣟⡽⣯⡻⣮⢳⡕⡧⣑⢇⠝⡔⢨⠂⡐⠀⠄⡁
⠀⠀⠀⢸⠐⡔⢱⠱⡨⡳⣹⢑⢭⢊⡿⣨⢇⢿⣺⣧⣻⣞⣽⣫⢾⣕⢯⡺⣢⠳⡱⠌⡢⢁⠌⢂⠠⠐
⠀⠀⠀⠕⡨⢈⠆⠳⡸⢨⡋⢢⠣⣘⢎⢎⢖⣟⢗⣿⣳⣟⢾⡳⣷⢝⣮⡻⣜⢕⢅⢣⢐⠡⢂⠡⠀⠠
⠀⠀⠀⢅⠨⠀⠎⡸⡡⢪⠐⡕⢌⢖⡱⣙⠂⠟⠝⢯⢷⣫⢟⡻⢼⣫⢾⡹⠪⠢⠃⠂⠀⠁⠠⠈⠀⠄
⠀⠀⠀⠢⢈⠌⠂⢔⠡⢊⢔⢅⠺⡔⡑⠬⢤⡢⣐⠄⢄⠤⡡⣾⢯⡳⠁⠀⠀⡀⢐⠌⡀⠢⠀⠠⠀⡀
⠀⠀⠀⢑⠠⢊⠂⢌⢢⠑⢅⢎⢕⠜⣜⣝⢾⡢⣎⢮⢪⡮⣻⣺⡯⣫⠂⠀⠀⠠⡱⢥⡩⡢⡰⠠⡁⠄
⠀⠀⠀⠀⠢⢁⠐⢅⠢⡑⡡⢨⣎⢾⢧⡿⣹⢮⢷⣝⢷⣯⣻⢾⣽⡣⡈⠀⠁⠐⡑⢜⠬⡪⡘⠔⠠⠀
⠀⠀⠀⠀⠁⡄⡁⠢⠐⠄⢂⢜⢮⣟⢷⣻⣽⢯⡷⣻⢯⢾⡽⣷⢯⡗⠄⠈⠀⠈⢌⠪⣊⢎⠨⠂⠐⠀
⠀⠀⠀⠀⠀⠢⢀⠑⡁⡊⡐⢘⢷⡽⣫⣷⣻⡳⣟⢵⢯⣳⣟⣽⣟⣕⢁⠀⠁⠀⠠⠣⡊⢆⠁⠂⠀⠀
⠀⠀⠀⠀⠀⠈⠢⡀⡑⠄⡘⢨⡗⣽⢳⡽⡮⣫⣪⡷⣯⠾⣳⢟⡮⡳⠀⠄⠁⢀⠀⠑⢌⠢⠁⠠⠀⠀
⠀⠀⠀⠀⠀⠈⠐⠀⢐⠐⢈⠄⡻⣜⢗⡽⣪⢞⡵⡻⣎⣗⠷⡵⢬⢤⠠⡀⠄⡠⠐⢀⠂⢂⠐⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⠁⠄⡀⠂⠔⢘⢎⢗⡽⣪⡳⣉⡞⠷⠝⠿⡳⣕⢯⠮⢊⠢⠐⠀⢁⠀⠠⠀⢀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠐⠠⠀⠌⠀⠠⣋⢮⡪⣗⢽⣪⣟⢟⡟⡷⢶⠦⢦⠲⡠⢂⠐⠈⠄⡁⠂⠠⠀⠀⠀
⠀⠀⠀⠀⠀⠄⢁⠈⡀⠂⠐⠀⠀⢧⢪⡺⣜⡵⣳⢝⡯⣞⢗⠦⣓⢔⢌⡢⠂⠌⡀⠄⠀⠂⠐⠀⠀⠀
⠀⠀⠀⠠⠈⠄⠠⠀⠄⢁⠈⠀⠀⢕⢕⠽⡬⡺⡕⣯⢻⣺⡳⣻⢎⡾⡸⢌⠓⡅⢐⠀⠁⠐⠀⠀⠄⠀
⠀⠠⡈⢄⠑⡀⢁⠐⢀⠂⠐⠀⠀⢂⢣⠻⣜⢵⡪⠳⡝⡮⣹⢣⠫⡜⢕⠕⡁⠢⠀⡀⠁⠀⠐⠀⠀⠀
⢀⠀⢌⠂⠔⠀⠄⠂⠄⡈⠀⠀⠀⠠⢑⢝⢪⢎⣗⢝⢮⣘⢌⠕⡑⢌⠊⠄⠐⢀⠀⠀⠀⠂⠀⠄⠀⠀
EOF
)

SITE_DESCRIPTION=$(cat << EOF
# Olá! Tudo bem com você?

Seja bem-vindo(a) a minha cápsula!

Eu ainda sou novo aqui, mas espero aprender a me virar.

Esta cápsula vai funcionar +/- como um "alter ego" do meu site da Web:
=> https://tukainpng.neocities.org

Com a diferença sendo, obviamente, que aqui tudo é beeem mais simples.
EOF
)

SITE_PAGES=$(cat << EOF
=> ./sobre.gmi 🫠 Sobre mim
=> ./leitura.gmi 📚 Lista de leitura
=> ./games.gmi 🎮 Minha coleção de jogos
=> ./log/ 📓 Gemlog
EOF
)

################################################################################

sample() {
  cat << EOF > content/1964-04-08-000-página-de-teste.gmi
\`\`\`
Pegou a referência? Essa data é a data de lançamento da Gemini, da Nasa
\`\`\`

# Título

## Subtítulo

### Sub-subtítulo

* Uma
* Lista

=> ../../../../../ Um link

> Uma citação
EOF
}

slug_basename() {
  basename $(echo $FILE \
      | awk -F'[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{3}-' '{print $2}' \
      | sed \
        -e 's/ç/c/g' \
        -e 's/ã/a/g' \
        -e 's/â/a/g' \
        -e 's/á/a/g' \
        -e 's/à/a/g' \
        -e 's/í/i/g' \
        -e 's/é/e/g' \
        -e 's/è/e/g' \
        -e 's/ê/e/g' \
        -e 's/ô/o/g' \
        -e 's/ó/o/g' \
        -e 's/ò/o/g' \
        -e 's/ò/o/g' \
        -e 's/õ/o/g') .gmi
}

post_dates() {
  POST_YEAR=$(echo $FILE  | awk -F'-' '{print $1}')
  POST_MONTH=$(echo $FILE | awk -F'-' '{print $2}')
  POST_DAY=$(echo $FILE   | awk -F'-' '{print $3}')
}

create_html() {
local OLD_IFS="$IFS"
local IFS="
"
local INSIDE_PRE=0

cat << EOF
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="$SITE_AUTHOR" />
    <title>$SITE_NAME</title>
  </head>
  <style>
  * {
    margin: 0;
    padding : 0;
  }

  :root {
    --bg: #1c1b19;
    --fg: #fce8c3;
    --lk: #2c78bf;
    --l2: #68a8e4;
    --qb: #202020;
    --qt: #e02c6d;
    --cd: #ff8700;
    --h1: #98bc37;
    --h2: #fbb829;
    --h3: #ff5f00;
  }

  @media only screen and (prefers-color-scheme: light) {
    :root {
      --bg: #feedf3;
      --fg: #33292b;
      --lk: #006e93;
      --l2: #1d8991;
      --qb: #f8e2e7;
      --qt: #df2d52;
      --cd: #f6661e;
      --h1: #2e916d;
      --h2: #5e2180;
      --h3: #c29461;
    }
  }

  body {
    background-color: var(--bg);
    color: var(--fg);
    padding: 1em;
    max-width: 80ch;
    display: block;
    margin: auto;
    font-family: sans;
  }

  h1, h2, h3 {
    margin-bottom: -1em;
  }

  h1 {
    color: var(--h1);
  }

  h2 {
    color: var(--h2);
  }

  h3 {
    color: var(--h3);
  }

  a {
    color: var(--lk);
    text-decoration: none;
    display: block;
    margin-bottom: -1.5em;

    &:hover {
      color: var(--l2);
    }
  }

  blockquote {
    background-color: var(--qb);
    padding: 1em;
    margin-bottom: -1em;
    border-left: solid 5px var(--qt);
    color: var(--qt);
  }

  pre {
    color: var(--cd);
    padding-top: 1em;
    padding-bottom: 1em;
    padding-left: auto;
    padding-right: auto;
    margin-bottom: 1em;
    margin-top: -1em;
    overflow-x: scroll;

    br {
      display: none;
    }
  }

  li {
    list-style-position: inside;
    margin-top: -1em;
    color: var(--h3);
  }

  li + br {
    display: none;
  }

  hr {
    border-top: dashed 1px var(--fg);
    border-bottom: 0;
    margin-bottom: -1em;
  }

  </style>
  <body>
EOF

for LINE in $(cat $1)
do
  if [ $LINE = '```' ]; then
    if [ "$INSIDE_PRE" -eq 0 ]; then
      printf '<pre>'
      INSIDE_PRE=1
    else
      printf '</pre>'
      INSIDE_PRE=0
    fi
    else
      echo $LINE | sed \
        -e 's#=> \([^ ]*\) \(.*\)#<a href="\1">\2</a>#' \
        -e 's#=> \(.*\)#<a href="\1">\1</a>#' \
        -e 's/^### \(.*\)/<h3>\1<\/h3>/' \
        -e 's/^## \(.*\)/<h2>\1<\/h2>/' \
        -e 's/^# \(.*\)/<h1>\1<\/h1>/' \
        -e 's#^\* \(.*\)#<li>\1</li>#' \
        -e 's#^> \(.*\)#<blockquote><p>\1</p></blockquote>#' \
        -e 's#^---------.*$#<hr>#' \
        -e 's/$/<br><br>/g'
  fi
done

cat << EOF
  </body>
</html>
EOF

local IFS="OLD_IFS"
}

create_capsule() {
  mkdir -p content public/log

  cp *.gmi public
  cat << EOF > public/index.gmi
\`\`\`
$(figlet -f slant "$SITE_NAME")
\`\`\`
\`\`\`
$SITE_BANNER
\`\`\`

$SITE_DESCRIPTION

-----------------------------------------------------------------------

$SITE_PAGES

-----------------------------------------------------------------------

=> https://tukainpng.neocities.org/#about Criado por tukain
EOF

  for FILE in $(ls ./content)
  do
    post_dates
    OUT_DIR_BASENAME=$(slug_basename)
    OUT_DIR="public/log/posts/$POST_YEAR/$POST_MONTH/$POST_DAY/$OUT_DIR_BASENAME"
    OUT_FILE="$OUT_DIR/index.gmi"
    mkdir -p $OUT_DIR

    if [ "$SITE_GENERATE_HTML" = "true" ]; then
      OUT_DIR_HTML="html/log/posts/$POST_YEAR/$POST_MONTH/$POST_DAY/$OUT_DIR_BASENAME"
      OUT_FILE_HTML="$OUT_DIR_HTML/index.html"
      mkdir -p $OUT_DIR_HTML
    fi

    cat << EOF > $OUT_FILE
=> /log/ ⬅️  Voltar

\`\`\`
$(figlet -f small "$POST_DAY / $POST_MONTH / $POST_YEAR")
\`\`\`

$(cat ./content/$FILE)

-- $SITE_AUTHOR, $POST_DAY/$POST_MONTH/$POST_YEAR
EOF

    [ "$SITE_GENERATE_HTML" = "true" ] && create_html $OUT_FILE > $OUT_FILE_HTML
  done

  [ "$SITE_GENERATE_HTML" = "true" ] && for FILE in $(ls public/*.gmi)
  do
    create_html $FILE > ./html/$(basename $FILE .gmi).temp
    cat ./html/$(basename $FILE .gmi).temp | sed 's/\.gmi/\.html/g' > ./html/$(basename $FILE .gmi).html
    rm ./html/$(basename $FILE .gmi).temp
  done

if [ "$SITE_FEED" = "true" ]; then
SITE_URL="gemini://tukain.flounder.online"
cat << EOF > ./public/rss.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
<title>$SITE_NAME</title>
<link>$SITE_URL</link>
<description>Feed RSS da minha cápsula Gemini</description>
EOF
fi

  cat << EOF > public/log/index.gmi
=> / ⬅️  Voltar

\`\`\`
$(figlet -f slant "Gemlog")
\`\`\`

EOF

  for FILE in $(ls ./content | sort -r)
  do
    post_dates
    POST_BASENAME=$(slug_basename)
    POST_URL="/log/posts/$POST_YEAR/$POST_MONTH/$POST_DAY/$POST_BASENAME/"
    POST_TITLE="($POST_DAY/$POST_MONTH/$POST_YEAR)\t$(basename "$(echo $FILE \
      | awk -F'[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{3}-' '{print $2}' \
      | tr '-' ' ')" .gmi)"
    printf "=> $POST_URL $POST_TITLE\n" >> public/log/index.gmi
    if [ "$SITE_FEED" = "true" ]; then
      echo "<item>
              <title>$(echo $POST_TITLE | sed 's/\\t/\t/g')</title>
              <link>$SITE_URL$POST_URL</link>
              <guid>$SITE_URL$POST_URL</guid>
              <pubDate>$(date '+%a, %d %b %Y %T GMT' --date=$POST_YEAR-$POST_MONTH-$POST_DAY)</pubDate>
            </item>" >> ./public/rss.xml
    fi
    done

  cat << EOF >> public/log/index.gmi

-----------------------------------------------------------------------

\`\`\`
Git hash: $(git log | head -n1 | awk '{print $2}')
Data e hora de compilação: $(date '+%d/%m/%Y - %H:%M:%S')

$(cowsay $(fortune "frases/brasil"))
\`\`\`
EOF

  [ "$SITE_GENERATE_HTML" = "true" ] && create_html public/log/index.gmi | sed 's/\t/<spam style="display: inline-block; width: 20px"><\/spam>/g' > html/log/index.html

  if [ "$SITE_FEED" = "true" ]; then
cat << EOF >> ./public/rss.xml
</channel>
</rss>
EOF
fi
}

new_post() {
  [ -z "$EDITOR" ] && EDITOR=vim
  printf "Título do post: "
  read TITLE
  TITLE="$(echo $TITLE | tr ' ' '-')"
  $EDITOR content/"$(date '+%Y-%m-%d')-000-$TITLE"
}

version() {
  printf "\033[32mblog.gmi \033[34m(v0.0.1)\033[0m\n"
}

case "$INPUT" in
  "create") create_capsule;;
  "version") version;;
  "new") new_post;;
  *) cat << EOF

Usage: capsule  <command>

version - shows version number
create  - create the capsule
new     - new post

EOF
;;
esac
