#!/bin/sh
INPUT=$1 # DON'T CHANGE THIS
set -e

################################################################################

SITE_NAME="Tukain"
SITE_AUTHOR="tukain"
SITE_FEED="true"
SITE_BANNER=$(cat << EOF
⠀⠀⠀⢠⢡⢯⣟⢮⢿⢾⣯⣻⣟⣾⣵⣿⢾⡟⠕⣁⢪⣮⣳⢯⣳⢕⢧⡳⡘⣌⢳⡐⢀⠂⠐⢂⠀⡀
⠀⠀⠀⢰⢍⡾⣳⡫⣟⣫⣷⢯⣿⡱⣿⢞⣿⡝⣜⢮⣟⣷⡻⣗⡽⣪⢳⡸⣊⢆⢎⠔⡁⠐⡀⠁⡂⠀
⠀⠀⢀⠣⣸⢋⢮⠸⡕⣽⣏⣿⢊⡾⣝⡿⣺⠔⣽⣻⣯⢿⣝⢷⡝⣮⢣⢎⢖⠅⡧⢊⠔⠁⢄⠀⠌⠠
⠀⠀⡀⠢⡣⡱⡑⢕⡺⣹⢖⡯⢸⡣⣻⣝⢽⢸⡿⣯⣟⡽⣯⡻⣮⢳⡕⡧⣑⢇⠝⡔⢨⠂⡐⠀⠄⡁
⠀⠀⠀⢸⠐⡔⢱⠱⡨⡳⣹⢑⢭⢊⡿⣨⢇⢿⣺⣧⣻⣞⣽⣫⢾⣕⢯⡺⣢⠳⡱⠌⡢⢁⠌⢂⠠⠐
⠀⠀⠀⠕⡨⢈⠆⠳⡸⢨⡋⢢⠣⣘⢎⢎⢖⣟⢗⣿⣳⣟⢾⡳⣷⢝⣮⡻⣜⢕⢅⢣⢐⠡⢂⠡⠀⠠
⠀⠀⠀⢅⠨⠀⠎⡸⡡⢪⠐⡕⢌⢖⡱⣙⠂⠟⠝⢯⢷⣫⢟⡻⢼⣫⢾⡹⠪⠢⠃⠂⠀⠁⠠⠈⠀⠄
⠀⠀⠀⠢⢈⠌⠂⢔⠡⢊⢔⢅⠺⡔⡑⠬⢤⡢⣐⠄⢄⠤⡡⣾⢯⡳⠁⠀⠀⡀⢐⠌⡀⠢⠀⠠⠀⡀
⠀⠀⠀⢑⠠⢊⠂⢌⢢⠑⢅⢎⢕⠜⣜⣝⢾⡢⣎⢮⢪⡮⣻⣺⡯⣫⠂⠀⠀⠠⡱⢥⡩⡢⡰⠠⡁⠄
⠀⠀⠀⠀⠢⢁⠐⢅⠢⡑⡡⢨⣎⢾⢧⡿⣹⢮⢷⣝⢷⣯⣻⢾⣽⡣⡈⠀⠁⠐⡑⢜⠬⡪⡘⠔⠠⠀
⠀⠀⠀⠀⠁⡄⡁⠢⠐⠄⢂⢜⢮⣟⢷⣻⣽⢯⡷⣻⢯⢾⡽⣷⢯⡗⠄⠈⠀⠈⢌⠪⣊⢎⠨⠂⠐⠀
⠀⠀⠀⠀⠀⠢⢀⠑⡁⡊⡐⢘⢷⡽⣫⣷⣻⡳⣟⢵⢯⣳⣟⣽⣟⣕⢁⠀⠁⠀⠠⠣⡊⢆⠁⠂⠀⠀
⠀⠀⠀⠀⠀⠈⠢⡀⡑⠄⡘⢨⡗⣽⢳⡽⡮⣫⣪⡷⣯⠾⣳⢟⡮⡳⠀⠄⠁⢀⠀⠑⢌⠢⠁⠠⠀⠀
⠀⠀⠀⠀⠀⠈⠐⠀⢐⠐⢈⠄⡻⣜⢗⡽⣪⢞⡵⡻⣎⣗⠷⡵⢬⢤⠠⡀⠄⡠⠐⢀⠂⢂⠐⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⠁⠄⡀⠂⠔⢘⢎⢗⡽⣪⡳⣉⡞⠷⠝⠿⡳⣕⢯⠮⢊⠢⠐⠀⢁⠀⠠⠀⢀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠐⠠⠀⠌⠀⠠⣋⢮⡪⣗⢽⣪⣟⢟⡟⡷⢶⠦⢦⠲⡠⢂⠐⠈⠄⡁⠂⠠⠀⠀⠀
⠀⠀⠀⠀⠀⠄⢁⠈⡀⠂⠐⠀⠀⢧⢪⡺⣜⡵⣳⢝⡯⣞⢗⠦⣓⢔⢌⡢⠂⠌⡀⠄⠀⠂⠐⠀⠀⠀
⠀⠀⠀⠠⠈⠄⠠⠀⠄⢁⠈⠀⠀⢕⢕⠽⡬⡺⡕⣯⢻⣺⡳⣻⢎⡾⡸⢌⠓⡅⢐⠀⠁⠐⠀⠀⠄⠀
⠀⠠⡈⢄⠑⡀⢁⠐⢀⠂⠐⠀⠀⢂⢣⠻⣜⢵⡪⠳⡝⡮⣹⢣⠫⡜⢕⠕⡁⠢⠀⡀⠁⠀⠐⠀⠀⠀
⢀⠀⢌⠂⠔⠀⠄⠂⠄⡈⠀⠀⠀⠠⢑⢝⢪⢎⣗⢝⢮⣘⢌⠕⡑⢌⠊⠄⠐⢀⠀⠀⠀⠂⠀⠄⠀⠀
EOF
)

SITE_DESCRIPTION=$(cat << EOF
# Olá! Tudo bem com você?

Seja bem-vindo(a) a minha cápsula!

Eu ainda sou novo aqui, mas espero aprender a me virar.

Esta cápsula vai funcionar +/- como um "alter ego" do meu site da Web:
=> https://tukainpng.neocities.org

Com a diferença sendo, obviamente, que aqui tudo é beeem mais simples.
EOF
)

SITE_PAGES=$(cat << EOF
=> ./leitura.gmi 📚 Lista de leitura
=> ./games.gmi 🎮 Minha coleção de jogos
=> ./log/ 📓 Gemlog
EOF
)

################################################################################

sample() {
  cat << EOF > content/1964-04-08-página-de-teste.gmi
\`\`\`
Pegou a referência? Essa data é a data de lançamento da Gemini, da Nasa
\`\`\`

# Título

## Subtítulo

### Sub-subtítulo

* Uma
* Lista

=> ../../../../../ Um link

> Uma citação
EOF
}

slug_basename() {
  basename $(echo $FILE \
      | awk -F'[0-9]{4}-[0-9]{2}-[0-9]{2}-' '{print $2}' \
      | sed \
        -e 's/ç/c/g' \
        -e 's/ã/a/g' \
        -e 's/â/a/g' \
        -e 's/á/a/g' \
        -e 's/à/a/g' \
        -e 's/í/i/g' \
        -e 's/é/e/g' \
        -e 's/è/e/g' \
        -e 's/ê/e/g' \
        -e 's/ô/o/g' \
        -e 's/ó/o/g' \
        -e 's/ò/o/g' \
        -e 's/ò/o/g' \
        -e 's/õ/o/g') .gmi
}

post_dates() {
  POST_YEAR=$(echo $FILE  | awk -F'-' '{print $1}')
  POST_MONTH=$(echo $FILE | awk -F'-' '{print $2}')
  POST_DAY=$(echo $FILE   | awk -F'-' '{print $3}')
}

create_capsule() {
  mkdir -p content public/log

  cp *.gmi public
  echo '```' >  public/index.gmi
  figlet -f slant "$SITE_NAME" >> public/index.gmi
  echo '```' >>  public/index.gmi
  echo '```' >>  public/index.gmi
  echo "$SITE_BANNER" >> public/index.gmi
  echo '```' >>  public/index.gmi
  echo "" >> public/index.gmi
  echo "$SITE_DESCRIPTION" >> public/index.gmi
  echo "" >> public/index.gmi
  echo "-----------------------------------------------------------------------" >> public/index.gmi
  echo "" >> public/index.gmi
  echo "$SITE_PAGES" >> public/index.gmi
  echo "" >> public/index.gmi
  echo "-----------------------------------------------------------------------" >> public/index.gmi
  echo "" >> public/index.gmi
  echo "=> https://tukainpng.neocities.org/#about Criado por tukain" >> public/index.gmi

  for FILE in $(ls ./content)
  do
    post_dates
    OUT_DIR_BASENAME=$(slug_basename)
    OUT_DIR="public/log/posts/$POST_YEAR/$POST_MONTH/$POST_DAY/$OUT_DIR_BASENAME"
    OUT_FILE="$OUT_DIR/index.gmi"
    mkdir -p $OUT_DIR
    echo "=> /log/ ⬅️  Voltar" >  $OUT_FILE
    echo "" >>  $OUT_FILE
    echo '```' >>  $OUT_FILE
    figlet -f small "$POST_DAY / $POST_MONTH / $POST_YEAR" >>  $OUT_FILE
    echo '```' >>  $OUT_FILE
    echo "" >>  $OUT_FILE
    cat ./content/$FILE >> $OUT_FILE
    echo "" >> $OUT_FILE
    echo "" >> $OUT_FILE
    echo "-- $SITE_AUTHOR, $POST_DAY/$POST_MONTH/$POST_YEAR" >> $OUT_FILE
  done

if [ "$SITE_FEED" == "true" ]; then
SITE_URL="gemini://tukain.flounder.online"
cat << EOF > ./public/rss.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
<channel>
<title>$SITE_NAME</title>
<link>$SITE_URL</link>
<description>Feed RSS da minha cápsula Gemini</description>
EOF
fi

  echo "=> / ⬅️  Voltar" > public/log/index.gmi
  echo "" >> public/log/index.gmi
  echo '```' >> public/log/index.gmi
  figlet -f slant "Gemlog" >> public/log/index.gmi
  echo '```' >> public/log/index.gmi
  echo "" >> public/log/index.gmi
  for FILE in $(ls ./content | sort -r)
  do
    post_dates
    POST_BASENAME=$(slug_basename)
    POST_URL="/log/posts/$POST_YEAR/$POST_MONTH/$POST_DAY/$POST_BASENAME/"
    POST_TITLE="($POST_DAY/$POST_MONTH/$POST_YEAR)\t$(basename "$(echo $FILE \
      | awk -F'[0-9]{4}-[0-9]{2}-[0-9]{2}-' '{print $2}' \
      | tr '-' ' ')" .gmi)"
    echo -e "=> $POST_URL $POST_TITLE" >> public/log/index.gmi
    if [ "$SITE_FEED" == "true" ]; then
      echo "<item>
              <title>$(echo $POST_TITLE | sed 's/\\t/\t/g')</title>
              <link>$SITE_URL$POST_URL</link>
              <guid>$SITE_URL$POST_URL</guid>
              <pubDate>$(date '+%a, %d %b %Y %T GMT' --date=$POST_YEAR-$POST_MONTH-$POST_DAY)</pubDate>
            </item>" >> ./public/rss.xml
    fi
    done

  echo "" >> public/log/index.gmi
  echo "-----------------------------------------------------------------------" >> public/log/index.gmi
  echo "" >> public/log/index.gmi
  echo '```' >> public/log/index.gmi
  echo "Git hash: $(git log | head -n1 | awk '{print $2}')" >> public/log/index.gmi
  echo "Data e hora de compilação: $(date '+%d/%m/%Y - %H:%M:%S')" >> public/log/index.gmi
  echo "Frase da sorte:" >> public/log/index.gmi
  echo "" >> public/log/index.gmi
  echo "$(fortune ~/.local/share/brasil)" >> public/log/index.gmi
  echo '```' >> public/log/index.gmi

if [ "$SITE_FEED" == "true" ]; then
cat << EOF >> ./public/rss.xml
</channel>
</rss>
EOF
fi
}

version() {
  printf "\033[32mblog.gmi \033[34m(v0.0.1)\033[0m\n"
}

case "$INPUT" in
  "create") create_capsule;;
  "version") version;;
  *) cat << EOF

Usage: capsule  <command>

version - shows version number
create  - create the capsule

EOF
;;
esac
